dist: trusty
sudo: required
language: c
cache:
  ccache: true
  directories:
  - ${HOME}/SageMath-7.6
  - ${HOME}/SageMath-8.0
  timeout: 1000
env:
  - SAGE_VERSION="7.6"
  - SAGE_VERSION="8.0"
before_install:
  - export SAGE_MIRROR="http://mirrors.mit.edu/sage/linux/64bit"
  - export SAGE_BINARY="sage-${SAGE_VERSION}-Ubuntu_14.04-x86_64.tar.bz2"
  - export SAGE_ROOT="${HOME}/SageMath-${SAGE_VERSION}"
  - export SAGE="${SAGE_ROOT}/sage"
  - echo ${SAGE_ROOT}
  - echo ${SAGE}
  - sudo apt-get -qq update
  - sudo apt-get install gcc g++ gfortran
# command to install dependencies
install: 
  - bash -x .travis_sage_install.sh
  - ${SAGE} --version
  - which gcc
  - ${SAGE} -sh -c "which gcc"
  - ${SAGE} -pip install --verbose --no-index --user .
  - export SURFACE_DYNAMICS_PATH="$(${SAGE} -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"
# command to run tests
script:
  - ${SAGE} -t --force-lib --long ${SURFACE_DYNAMICS_PATH}
  - cd doc/
  - ${SAGE} -sh -c "make html"
